// <auto-generated />
using System;
using EfcDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcDataAccess.Migrations
{
    [DbContext(typeof(SmartHomeSystemContext))]
    [Migration("20231107101812_SmartHomeDBInitial")]
    partial class SmartHomeDBInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Entities.Home", b =>
                {
                    b.Property<long>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceEui")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HomeId");

                    b.HasIndex("DeviceEui")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Entities.LastMeasurement", b =>
                {
                    b.Property<int>("LastMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceEui")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastDataMeasurementSensorDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("LastMeasurementId");

                    b.HasIndex("LastDataMeasurementSensorDataId");

                    b.ToTable("LastMeasurements");
                });

            modelBuilder.Entity("Entities.RoomProfile", b =>
                {
                    b.Property<long>("RoomProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("IdealHumidity")
                        .HasColumnType("REAL");

                    b.Property<float>("IdealTemperature")
                        .HasColumnType("REAL");

                    b.Property<long>("LimitsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomProfileId");

                    b.HasIndex("HomeId");

                    b.HasIndex("LimitsId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomProfiles");
                });

            modelBuilder.Entity("Entities.SensorData", b =>
                {
                    b.Property<int>("SensorDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("HumidityData")
                        .HasColumnType("REAL");

                    b.Property<long?>("RoomProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TemperatureData")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("SensorDataId");

                    b.HasIndex("HomeId");

                    b.HasIndex("RoomProfileId");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("Entities.ThresholdLimits", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("HumidityMax")
                        .HasColumnType("REAL");

                    b.Property<float>("HumidityMin")
                        .HasColumnType("REAL");

                    b.Property<float>("TemperatureMax")
                        .HasColumnType("REAL");

                    b.Property<float>("TemperatureMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ThresholdsLimits");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Home", b =>
                {
                    b.HasOne("Entities.User", null)
                        .WithMany("Homes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.LastMeasurement", b =>
                {
                    b.HasOne("Entities.SensorData", "LastDataMeasurement")
                        .WithMany()
                        .HasForeignKey("LastDataMeasurementSensorDataId");

                    b.Navigation("LastDataMeasurement");
                });

            modelBuilder.Entity("Entities.RoomProfile", b =>
                {
                    b.HasOne("Entities.Home", null)
                        .WithMany("RoomProfiles")
                        .HasForeignKey("HomeId");

                    b.HasOne("Entities.ThresholdLimits", "Limits")
                        .WithMany()
                        .HasForeignKey("LimitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.User", null)
                        .WithMany("RoomProfiles")
                        .HasForeignKey("UserId");

                    b.Navigation("Limits");
                });

            modelBuilder.Entity("Entities.SensorData", b =>
                {
                    b.HasOne("Entities.Home", null)
                        .WithMany("Measurements")
                        .HasForeignKey("HomeId");

                    b.HasOne("Entities.RoomProfile", null)
                        .WithMany("Measurements")
                        .HasForeignKey("RoomProfileId");
                });

            modelBuilder.Entity("Entities.Home", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("RoomProfiles");
                });

            modelBuilder.Entity("Entities.RoomProfile", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Homes");

                    b.Navigation("RoomProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
