// <auto-generated />
using System;
using EfcDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfcDataAccess.Migrations
{
    [DbContext(typeof(SmartHomeSystemContext))]
    [Migration("20231122094819_CloudDB_init")]
    partial class CloudDB_init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Home", b =>
                {
                    b.Property<long>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HomeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CurrentRoomProfileRoomProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceEui")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("HomeId");

                    b.HasIndex("CurrentRoomProfileRoomProfileId");

                    b.HasIndex("DeviceEui")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("Entities.LastMeasurement", b =>
                {
                    b.Property<long>("LastMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LastMeasurementId"));

                    b.Property<string>("DeviceEui")
                        .HasColumnType("text");

                    b.Property<int?>("LastDataMeasurementSensorDataId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("LastMeasurementId");

                    b.HasIndex("LastDataMeasurementSensorDataId");

                    b.ToTable("LastMeasurement");
                });

            modelBuilder.Entity("Entities.RoomProfile", b =>
                {
                    b.Property<long>("RoomProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RoomProfileId"));

                    b.Property<long?>("HomeId")
                        .HasColumnType("bigint");

                    b.Property<float>("IdealHumidity")
                        .HasColumnType("real");

                    b.Property<float>("IdealTemperature")
                        .HasColumnType("real");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<long>("LimitsId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("RoomProfileId");

                    b.HasIndex("HomeId");

                    b.HasIndex("LimitsId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomProfiles");
                });

            modelBuilder.Entity("Entities.SensorData", b =>
                {
                    b.Property<int>("SensorDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorDataId"));

                    b.Property<long>("HomeId")
                        .HasColumnType("bigint");

                    b.Property<float>("HumidityData")
                        .HasColumnType("real");

                    b.Property<long?>("RoomProfileId")
                        .HasColumnType("bigint");

                    b.Property<float>("TemperatureData")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SensorDataId");

                    b.HasIndex("HomeId");

                    b.HasIndex("RoomProfileId");

                    b.ToTable("DataMeasures");
                });

            modelBuilder.Entity("Entities.ThresholdLimits", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("HumidityMax")
                        .HasColumnType("real");

                    b.Property<float>("HumidityMin")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureMax")
                        .HasColumnType("real");

                    b.Property<float>("TemperatureMin")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("ThresholdsLimits");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Home", b =>
                {
                    b.HasOne("Entities.RoomProfile", "CurrentRoomProfile")
                        .WithMany()
                        .HasForeignKey("CurrentRoomProfileRoomProfileId");

                    b.HasOne("Entities.User", null)
                        .WithMany("Homes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentRoomProfile");
                });

            modelBuilder.Entity("Entities.LastMeasurement", b =>
                {
                    b.HasOne("Entities.SensorData", "LastDataMeasurement")
                        .WithMany()
                        .HasForeignKey("LastDataMeasurementSensorDataId");

                    b.Navigation("LastDataMeasurement");
                });

            modelBuilder.Entity("Entities.RoomProfile", b =>
                {
                    b.HasOne("Entities.Home", null)
                        .WithMany("RoomProfiles")
                        .HasForeignKey("HomeId");

                    b.HasOne("Entities.ThresholdLimits", "Limits")
                        .WithMany()
                        .HasForeignKey("LimitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.User", null)
                        .WithMany("RoomProfiles")
                        .HasForeignKey("UserId");

                    b.Navigation("Limits");
                });

            modelBuilder.Entity("Entities.SensorData", b =>
                {
                    b.HasOne("Entities.Home", null)
                        .WithMany("Measurements")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.RoomProfile", null)
                        .WithMany("Measurements")
                        .HasForeignKey("RoomProfileId");
                });

            modelBuilder.Entity("Entities.Home", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("RoomProfiles");
                });

            modelBuilder.Entity("Entities.RoomProfile", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Homes");

                    b.Navigation("RoomProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
